### ISSUE TITLE
Fixed offset modifier does not take into account multiple child joint 

### ISSUE THREAD

**Issue by CarlottaSartore** [icub-tech-iit/urdf-modifiers#21]
In the fixed offset modifier, the situation in which a link has several child joints is not taken into account, 
indeed, only the first returned joint is taken into account 
https://github.com/icub-tech-iit/urdf-modifiers/blob/8a5b9bb6d0f76ac6706691695a2d88789f43a15c/urdfModifiers/core/fixedOffsetModifier.py#L90-L92
thus, in the case of the chest, torso1, torso2 link of the stickbot, the model is not modified correctly, since only one joint is considered. 

Maybe this issue is documented somewhere and I did not find it!

C.C. @GrmanRodriguez @AlexAntn  @traversaro

**Comment by GrmanRodriguez** [comment]
Solved in #24. Closing this issue.
