### ISSUE TITLE
Unable to install urdf-modifiers using installation instructions

### ISSUE THREAD

**Issue by claudia-lat** [icub-tech-iit/urdf-modifiers#40]
Today I've tried to install `urdf-modifiers`using the command ```pip install urdf-modifiers ```
 and it doesn't works.  Just to let you know a bit of context on the installation steps:

- I've created a new conda env
- I've installed python as included in `idyntree` by running 
  ```conda install -c conda-forge idyntree```
- I've cloned `urdf-modifiers` repo and launched ```pip install urdf-modifiers ``` --> failed
- I thought it was a matter of python version since the version installed via `idyntree` is `3.12.3` while `urdf-modifiers` requires `3.8` --> I've downgraded python version --> failed
- After an iteration with @CarlottaSartore, the installation worked:
  - by launching  ```pip install .```
  - with the python version `3.12.3`

**Comment by Nicogene** [comment]
Hi @claudia-lat !

Could you please put here the output of the failing `pip install urdf-modifiers` ? Thanks!

**Comment by claudia-lat** [comment]
@Nicogene, sorry but I have got only this pic
![09064e1d-3198-44c3-bb4d-70eecb3d9c26](https://github.com/icub-tech-iit/urdf-modifiers/assets/10923418/c23d3c10-c8d6-4c9c-aed2-173df7160440)

**Comment by claudia-lat** [comment]
@Nicogene sorry for this but I did not save the message!

**Comment by claudia-lat** [comment]
@Nicogene I've just redo the installation in a brand new env, this is the error

> (testenv) claudialatella@iiticublap159 ~/Documents/Repos/GITHUB/urdf-modifiers $pip install urdf-modifiers
> ERROR: Could not find a version that satisfies the requirement urdf-modifiers (from versions: none)
> ERROR: No matching distribution found for urdf-modifiers

**Comment by traversaro** [comment]
> @Nicogene I've just redo the installation in a brand new env, this is the error
> 
> > (testenv) claudialatella@iiticublap159 ~/Documents/Repos/GITHUB/urdf-modifiers $pip install urdf-modifiers
> > ERROR: Could not find a version that satisfies the requirement urdf-modifiers (from versions: none)
> > ERROR: No matching distribution found for urdf-modifiers

Apparently the job that was supposed to upload the package on 0.0.2 tag failed: https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/6848316286 . fyi @Nicogene @CarlottaSartore

**Comment by Nicogene** [comment]
> > @Nicogene I've just redo the installation in a brand new env, this is the error
> > > (testenv) claudialatella@iiticublap159 ~/Documents/Repos/GITHUB/urdf-modifiers $pip install urdf-modifiers
> > > ERROR: Could not find a version that satisfies the requirement urdf-modifiers (from versions: none)
> > > ERROR: No matching distribution found for urdf-modifiers
> 
> Apparently the job that was supposed to upload the package on 0.0.2 tag failed: [icub-tech-iit/urdf-modifiers/actions/runs/6848316286](https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/6848316286) . fyi @Nicogene @CarlottaSartore

Ah, I re-did the release, because it was too much time ago and we cannot see the log, let's see what is happening

- https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/9062401485

**Comment by Nicogene** [comment]
Here is the error:
```
Warning: Input 'password' has been deprecated with message: UNSUPPORTED GITHUB ACTION VERSION

You are using `pypa/gh-action-pypi-publish@master`. The `master` branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use `pypa/gh-action-pypi-publish@release/v1`. If you feel adventurous, you may opt to use use `pypa/gh-action-pypi-publish@unstable/v1` instead. A more general recommendation is to pin to exact tags or commit SHAs.

Please also consider migrating your setup to use secretless publishing: https://github.com/marketplace/actions/pypi-publish#trusted-publishing

https://stand-with-ukraine.pp.ua/

Run pypa/gh-action-pypi-publish@master
/usr/bin/docker run --name e679f4a535046c79d515a0c35974f91_95cdba --label 674617 --workdir /github/workspace --rm -e "INPUT_PASSWORD" -e "INPUT_USER" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP_EXISTING" -e "INPUT_VERBOSE" -e "INPUT_PRINT_HASH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/urdf-modifiers/urdf-modifiers":"/github/workspace" 674617:6e679f4a535046c79d515a0c35974f91  "__token__" "***
" "" "dist" "true" "false" "false" "false"
/app/twine-upload.sh: line 6: pypa/gh-action-pypi-publish@master: No such file or directory
/app/twine-upload.sh: line 6: master: command not found
/app/twine-upload.sh: line 6: pypa/gh-action-pypi-publish@release/v1: No such file or directory
/app/twine-upload.sh: line 6: pypa/gh-action-pypi-publish@unstable/v1: No such file or directory
Warning:  You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
Checking dist/urdf_modifiers-0.0.2-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         No content rendered from RST source.                                   
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking dist/urdf_modifiers-0.0.2.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
WARNING  `long_description` missing.
```

It is plenty of warnings by the way

**Comment by traversaro** [comment]
See https://github.com/ami-iit/resolve-robotics-uri-py/blob/main/.github/workflows/publish-to-pypi.yml for a simpler github actions job that worked (at least back in February).

**Comment by traversaro** [comment]
> See https://github.com/ami-iit/resolve-robotics-uri-py/blob/main/.github/workflows/publish-to-pypi.yml for a simpler github actions job that worked (at least back in February).

That script still works: https://github.com/ami-iit/resolve-robotics-uri-py/actions/runs/9080053869 .

**Comment by traversaro** [comment]
At least for urdf-modifiers 0.0.2, the issue was fixed manually and the package is now available in PyPI in https://pypi.org/project/urdf-modifiers/ .

**Comment by traversaro** [comment]
It will soon be available also con conda-forge: https://github.com/conda-forge/staged-recipes/pull/28004, once that is done I will update the README.
