### ISSUE TITLE
Tag 0.0.3 ?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/urdf-modifiers#42]
The 0.0.2 release is missing the `LICENSE` file, could we tag a new release (after updating the version number in https://github.com/icub-tech-iit/urdf-modifiers/blob/master/setup.cfg#L6 ?). Thanks! @Nicogene

**Comment by traversaro** [comment]
We can also use this to check if now the pypi upload works fine (it should as I configured on the pypi side to trust the github actions on this repo for uploading the release).

**Comment by Nicogene** [comment]
Yes! Here it is:
- https://github.com/icub-tech-iit/urdf-modifiers/releases/tag/v0.0.3

Closing

**Comment by Nicogene** [comment]
> We can also use this to check if now the pypi upload works fine (it should as I configured on the pypi side to trust the github actions on this repo for uploading the release).

Ah unfortunately it failed @traversaro 

https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/11519893861/job/32069983796

**Comment by Nicogene** [comment]
> > We can also use this to check if now the pypi upload works fine (it should as I configured on the pypi side to trust the github actions on this repo for uploading the release).
> 
> Ah unfortunately it failed [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1857049?s=64&amp;u=2178077c05edb1cff607766c0045015dbf112c00&amp;v=4">@traversaro](https://github.com/traversaro)
> 
> https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/11519893861/job/32069983796

I managed to fix the easiest error (deprecated version of download_artifacs), now it is failing for this:

```
Checking dist/urdf_modifiers-0.0.3-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         No content rendered from RST source.                                   
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking dist/urdf_modifiers-0.0.3.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
WARNING  `long_description` missing.  
```

from: https://github.com/icub-tech-iit/urdf-modifiers/actions/runs/11519965036/job/32070230348

**Comment by Nicogene** [comment]
I can try what copilot is saying :D 

![Image](https://github.com/user-attachments/assets/ab46b510-4af9-43c9-b920-4026784ed081)

Related to:
- https://github.com/icub-tech-iit/urdf-modifiers/issues/40

**Comment by traversaro** [comment]
See https://github.com/icub-tech-iit/urdf-modifiers/pull/43 for one side of it.
