### ISSUE TITLE
All existing multipliers assume that the rpy part of the visual origin is 0 0 0

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/urdf-modifiers#7]
I tried to use the `urdf-modifiers` with a model that have visual elements like:
~~~
    <visual>
      <origin xyz="-5.735652515724561e-4 -1.0710181526374374e-9 -0.01489637759328169" rpy="1.57079632679 -0 1.57079632679"/>
      <geometry>
        <box size="0.044000009540468454 0.05020724982023239 0.0561471302062273"/>
      </geometry>
    </visual>
~~~
and the code was not behaving as expected, as the code is ignoring the `rpy="1.57079632679 -0 1.57079632679"` attribute of the `visual.origin` element, silently assuming that it is `0.0 0.0 0.0`. 

Manually converting the visual (in particular the size of the box) to represent always the same shape, but with rpy 0 0 0 has been working as a workaround:
~~~
    <visual>
      <origin xyz="-5.735652515724561e-4 -1.0710181526374374e-9 -0.01489637759328169" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.0561471302062273 0.044000009540468454 0.05020724982023239"/>
      </geometry>
    </visual>
~~~

However, this is not possible for all shapes (in particular, it is not possbile for cylinders).

**Comment by GrmanRodriguez** [comment]
I am not entirely sure if we should allow different values of rpy. How would we calculate the link length if the link is not parallel to the joint? Seems like the expected behavior in those situations would be different in each case.

Still, I'll think about it more before giving a final opinion.

**Comment by traversaro** [comment]
> I am not entirely sure if we should allow different values of rpy. How would we calculate the link length if the link is not parallel to the joint? Seems like the expected behavior in those situations would be different in each case.
> 
> Still, I'll think about it more before giving a final opinion.

The shape "direction" may be parallel to the joint offset even if the rpy is not zero. Anyhow, even if we do not want to consider rpy, I guess it would be more user friendly to raise an error instead of silently ignoring it.

**Comment by traversaro** [comment]
In the new modifier developed for https://github.com/icub-tech-iit/urdf-modifiers/issues/11), some code to handle this case is https://github.com/traversaro/urdf-modifiers/blob/invariance2/examples/LinkAndJointModifierV1.py#L44 .

If instead you want to just have some code to raise an error if a visual has a rpy not 0 0 0:
~~~py
# We assume that rpy of visual transform is 0.0 0.0 0.0, i.e. identity 
        if (not np.all(np.isclose(self.get_visual().origin[0:3:1,0:3:1], np.eye(3,3)))):
           raise RuntimeError("Link " + link_element.name + " does not respect assumption as it has non-zero rpy values in visual origin transform.")
~~~
