### ISSUE TITLE
The library requires that the model contains a `<gazebo>` element

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/urdf-modifiers#8]
The library does not work as intended if an element `<gazebo>` is not present in hte file. A useful workaround is to add a: 
~~~
<gazebo></gazebo>
~~~
element in the document, right before the `</robot>` closing tag.

**Comment by GrmanRodriguez** [comment]
I was able to verify this. We expected some `<gazebo>` tags at the end of the URDF when we did `ergocub_gazebo_simiulations`. Fixed in [this PR](https://github.com/icub-tech-iit/urdf-modifiers/pull/12)
